update=30/08/2016 19:35:25
version=1
last_client=kicad
[cvpcb]
version=1
NetIExt=net
[pcbnew]
version=1
PageLayoutDescrFile=
LastNetListRead=poncho_grande.net
UseCmpFile=0
PadDrill=0.6
PadDrillOvalY=0.6
PadSizeH=1.4
PadSizeV=1.4
PcbTextSizeV=1.5
PcbTextSizeH=1.5
PcbTextThickness=0.3
ModuleTextSizeV=1e-06
ModuleTextSizeH=1e-06
ModuleTextSizeThickness=0.15
SolderMaskClearance=0.2
SolderMaskMinWidth=0
DrawSegmentWidth=0.2
BoardOutlineThickness=0.15
ModuleOutlineThickness=0.15
[general]
version=1
[eeschema]
version=1
LibDir=../../kicad/libModelos;../../kicad/libPonchos
[eeschema/libraries]
LibName1=PonchoERG-rescue
LibName2=Misc_Poncho_Grande
LibName3=Poncho_Esqueleto
LibName4=C:/Program Files/KiCad/share/kicad/library/74xgxx
LibName5=C:/Program Files/KiCad/share/kicad/library/74xx
LibName6=C:/Program Files/KiCad/share/kicad/library/ac-dc
LibName7=C:/Program Files/KiCad/share/kicad/library/actel
LibName8=C:/Program Files/KiCad/share/kicad/library/adc-dac
LibName9=C:/Program Files/KiCad/share/kicad/library/Altera
LibName10=C:/Program Files/KiCad/share/kicad/library/analog_devices
LibName11=C:/Program Files/KiCad/share/kicad/library/analog_switches
LibName12=C:/Program Files/KiCad/share/kicad/library/atmel
LibName13=C:/Program Files/KiCad/share/kicad/library/audio
LibName14=C:/Program Files/KiCad/share/kicad/library/brooktre
LibName15=C:/Program Files/KiCad/share/kicad/library/cmos_ieee
LibName16=C:/Program Files/KiCad/share/kicad/library/cmos4000
LibName17=C:/Program Files/KiCad/share/kicad/library/conn
LibName18=C:/Program Files/KiCad/share/kicad/library/contrib
LibName19=C:/Program Files/KiCad/share/kicad/library/cypress
LibName20=C:/Program Files/KiCad/share/kicad/library/dc-dc
LibName21=C:/Program Files/KiCad/share/kicad/library/device
LibName22=C:/Program Files/KiCad/share/kicad/library/digital-audio
LibName23=C:/Program Files/KiCad/share/kicad/library/diode
LibName24=C:/Program Files/KiCad/share/kicad/library/display
LibName25=C:/Program Files/KiCad/share/kicad/library/dsp
LibName26=C:/Program Files/KiCad/share/kicad/library/elec-unifil
LibName27=C:/Program Files/KiCad/share/kicad/library/ESD_Protection
LibName28=C:/Program Files/KiCad/share/kicad/library/ftdi
LibName29=C:/Program Files/KiCad/share/kicad/library/gennum
LibName30=C:/Program Files/KiCad/share/kicad/library/graphic
LibName31=C:/Program Files/KiCad/share/kicad/library/hc11
LibName32=C:/Program Files/KiCad/share/kicad/library/intel
LibName33=C:/Program Files/KiCad/share/kicad/library/interface
LibName34=C:/Program Files/KiCad/share/kicad/library/ir
LibName35=C:/Program Files/KiCad/share/kicad/library/Lattice
LibName36=C:/Program Files/KiCad/share/kicad/library/linear
LibName37=C:/Program Files/KiCad/share/kicad/library/logo
LibName38=C:/Program Files/KiCad/share/kicad/library/maxim
LibName39=C:/Program Files/KiCad/share/kicad/library/memory
LibName40=C:/Program Files/KiCad/share/kicad/library/microchip
LibName41=C:/Program Files/KiCad/share/kicad/library/microchip_dspic33dsc
LibName42=C:/Program Files/KiCad/share/kicad/library/microchip_pic10mcu
LibName43=C:/Program Files/KiCad/share/kicad/library/microchip_pic12mcu
LibName44=C:/Program Files/KiCad/share/kicad/library/microchip_pic16mcu
LibName45=C:/Program Files/KiCad/share/kicad/library/microchip_pic18mcu
LibName46=C:/Program Files/KiCad/share/kicad/library/microchip_pic32mcu
LibName47=C:/Program Files/KiCad/share/kicad/library/microcontrollers
LibName48=C:/Program Files/KiCad/share/kicad/library/motor_drivers
LibName49=C:/Program Files/KiCad/share/kicad/library/motorola
LibName50=C:/Program Files/KiCad/share/kicad/library/msp430
LibName51=C:/Program Files/KiCad/share/kicad/library/nordicsemi
LibName52=C:/Program Files/KiCad/share/kicad/library/nxp_armmcu
LibName53=C:/Program Files/KiCad/share/kicad/library/onsemi
LibName54=C:/Program Files/KiCad/share/kicad/library/opto
LibName55=C:/Program Files/KiCad/share/kicad/library/Oscillators
LibName56=C:/Program Files/KiCad/share/kicad/library/philips
LibName57=C:/Program Files/KiCad/share/kicad/library/power
LibName58=C:/Program Files/KiCad/share/kicad/library/Power_Management
LibName59=C:/Program Files/KiCad/share/kicad/library/powerint
LibName60=C:/Program Files/KiCad/share/kicad/library/pspice
LibName61=C:/Program Files/KiCad/share/kicad/library/references
LibName62=C:/Program Files/KiCad/share/kicad/library/regul
LibName63=C:/Program Files/KiCad/share/kicad/library/relays
LibName64=C:/Program Files/KiCad/share/kicad/library/rfcom
LibName65=C:/Program Files/KiCad/share/kicad/library/sensors
LibName66=C:/Program Files/KiCad/share/kicad/library/silabs
LibName67=C:/Program Files/KiCad/share/kicad/library/siliconi
LibName68=C:/Program Files/KiCad/share/kicad/library/stm8
LibName69=C:/Program Files/KiCad/share/kicad/library/stm32
LibName70=C:/Program Files/KiCad/share/kicad/library/supertex
LibName71=C:/Program Files/KiCad/share/kicad/library/switches
LibName72=C:/Program Files/KiCad/share/kicad/library/texas
LibName73=C:/Program Files/KiCad/share/kicad/library/transf
LibName74=C:/Program Files/KiCad/share/kicad/library/transistors
LibName75=C:/Program Files/KiCad/share/kicad/library/ttl_ieee
LibName76=C:/Program Files/KiCad/share/kicad/library/valves
LibName77=C:/Program Files/KiCad/share/kicad/library/video
LibName78=C:/Program Files/KiCad/share/kicad/library/Xicor
LibName79=C:/Program Files/KiCad/share/kicad/library/xilinx
LibName80=C:/Program Files/KiCad/share/kicad/library/Zilog
LibName81=libs/ADS1299
LibName82=libs/ADuM2401
LibName83=libs/ADuM6401
LibName84=libs/CKCL44X7R1H
LibName85=libs/GNDD
LibName86=libs/NetTie
LibName87=libs/PonchoERG
LibName88=libs/PonchoERG-cache
LibName89=libs/PonchoERG-rescue
LibName90=libs/Power
LibName91=libs/VCC
