update=13/09/2017 14:02:42
version=1
last_client=kicad
[cvpcb]
version=1
NetIExt=net
[pcbnew]
version=1
PageLayoutDescrFile=
LastNetListRead=poncho_grande.net
UseCmpFile=0
PadDrill=0.6
PadDrillOvalY=0.6
PadSizeH=1.4
PadSizeV=1.4
PcbTextSizeV=1.5
PcbTextSizeH=1.5
PcbTextThickness=0.3
ModuleTextSizeV=1e-06
ModuleTextSizeH=1e-06
ModuleTextSizeThickness=0.15
SolderMaskClearance=0.2
SolderMaskMinWidth=0
DrawSegmentWidth=0.2
BoardOutlineThickness=0.15
ModuleOutlineThickness=0.15
[general]
version=1
[eeschema]
version=1
LibDir=../../kicad/libModelos;../../kicad/libPonchos
[eeschema/libraries]
LibName1=PonchoERG-rescue
LibName2=libModelos/Misc_Poncho_Grande
LibName3=libPonchos/Poncho_Esqueleto
LibName4=libs/PonchoERG
LibName5=libs/power
LibName6=C:/Program Files/KiCad/share/kicad/library/74xgxx
LibName7=C:/Program Files/KiCad/share/kicad/library/74xx
LibName8=C:/Program Files/KiCad/share/kicad/library/ac-dc
LibName9=C:/Program Files/KiCad/share/kicad/library/actel
LibName10=C:/Program Files/KiCad/share/kicad/library/adc-dac
LibName11=C:/Program Files/KiCad/share/kicad/library/Altera
LibName12=C:/Program Files/KiCad/share/kicad/library/analog_devices
LibName13=C:/Program Files/KiCad/share/kicad/library/analog_switches
LibName14=C:/Program Files/KiCad/share/kicad/library/atmel
LibName15=C:/Program Files/KiCad/share/kicad/library/audio
LibName16=C:/Program Files/KiCad/share/kicad/library/brooktre
LibName17=C:/Program Files/KiCad/share/kicad/library/cmos_ieee
LibName18=C:/Program Files/KiCad/share/kicad/library/cmos4000
LibName19=C:/Program Files/KiCad/share/kicad/library/conn
LibName20=C:/Program Files/KiCad/share/kicad/library/contrib
LibName21=C:/Program Files/KiCad/share/kicad/library/cypress
LibName22=C:/Program Files/KiCad/share/kicad/library/dc-dc
LibName23=C:/Program Files/KiCad/share/kicad/library/device
LibName24=C:/Program Files/KiCad/share/kicad/library/digital-audio
LibName25=C:/Program Files/KiCad/share/kicad/library/diode
LibName26=C:/Program Files/KiCad/share/kicad/library/display
LibName27=C:/Program Files/KiCad/share/kicad/library/dsp
LibName28=C:/Program Files/KiCad/share/kicad/library/elec-unifil
LibName29=C:/Program Files/KiCad/share/kicad/library/ESD_Protection
LibName30=C:/Program Files/KiCad/share/kicad/library/ftdi
LibName31=C:/Program Files/KiCad/share/kicad/library/gennum
LibName32=C:/Program Files/KiCad/share/kicad/library/graphic
LibName33=C:/Program Files/KiCad/share/kicad/library/hc11
LibName34=C:/Program Files/KiCad/share/kicad/library/intel
LibName35=C:/Program Files/KiCad/share/kicad/library/interface
LibName36=C:/Program Files/KiCad/share/kicad/library/ir
LibName37=C:/Program Files/KiCad/share/kicad/library/Lattice
LibName38=C:/Program Files/KiCad/share/kicad/library/linear
LibName39=C:/Program Files/KiCad/share/kicad/library/logo
LibName40=C:/Program Files/KiCad/share/kicad/library/maxim
LibName41=C:/Program Files/KiCad/share/kicad/library/memory
LibName42=C:/Program Files/KiCad/share/kicad/library/microchip
LibName43=C:/Program Files/KiCad/share/kicad/library/microchip_dspic33dsc
LibName44=C:/Program Files/KiCad/share/kicad/library/microchip_pic10mcu
LibName45=C:/Program Files/KiCad/share/kicad/library/microchip_pic12mcu
LibName46=C:/Program Files/KiCad/share/kicad/library/microchip_pic16mcu
LibName47=C:/Program Files/KiCad/share/kicad/library/microchip_pic18mcu
LibName48=C:/Program Files/KiCad/share/kicad/library/microchip_pic32mcu
LibName49=C:/Program Files/KiCad/share/kicad/library/microcontrollers
LibName50=C:/Program Files/KiCad/share/kicad/library/motor_drivers
LibName51=C:/Program Files/KiCad/share/kicad/library/motorola
LibName52=C:/Program Files/KiCad/share/kicad/library/msp430
LibName53=C:/Program Files/KiCad/share/kicad/library/nordicsemi
LibName54=C:/Program Files/KiCad/share/kicad/library/nxp_armmcu
LibName55=C:/Program Files/KiCad/share/kicad/library/onsemi
LibName56=C:/Program Files/KiCad/share/kicad/library/opto
LibName57=C:/Program Files/KiCad/share/kicad/library/Oscillators
LibName58=C:/Program Files/KiCad/share/kicad/library/philips
LibName59=C:/Program Files/KiCad/share/kicad/library/power
LibName60=C:/Program Files/KiCad/share/kicad/library/Power_Management
LibName61=C:/Program Files/KiCad/share/kicad/library/powerint
LibName62=C:/Program Files/KiCad/share/kicad/library/pspice
LibName63=C:/Program Files/KiCad/share/kicad/library/references
LibName64=C:/Program Files/KiCad/share/kicad/library/regul
LibName65=C:/Program Files/KiCad/share/kicad/library/relays
LibName66=C:/Program Files/KiCad/share/kicad/library/rfcom
LibName67=C:/Program Files/KiCad/share/kicad/library/sensors
LibName68=C:/Program Files/KiCad/share/kicad/library/silabs
LibName69=C:/Program Files/KiCad/share/kicad/library/siliconi
LibName70=C:/Program Files/KiCad/share/kicad/library/stm8
LibName71=C:/Program Files/KiCad/share/kicad/library/stm32
LibName72=C:/Program Files/KiCad/share/kicad/library/supertex
LibName73=C:/Program Files/KiCad/share/kicad/library/switches
LibName74=C:/Program Files/KiCad/share/kicad/library/texas
LibName75=C:/Program Files/KiCad/share/kicad/library/transf
LibName76=C:/Program Files/KiCad/share/kicad/library/transistors
LibName77=C:/Program Files/KiCad/share/kicad/library/ttl_ieee
LibName78=C:/Program Files/KiCad/share/kicad/library/valves
LibName79=C:/Program Files/KiCad/share/kicad/library/video
LibName80=C:/Program Files/KiCad/share/kicad/library/Xicor
LibName81=C:/Program Files/KiCad/share/kicad/library/xilinx
LibName82=C:/Program Files/KiCad/share/kicad/library/Zilog
LibName83=libs/Jumpers_Config
LibName84=libs/Jumpers_Default
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=doc/
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=
SpiceForceRefPrefix=0
SpiceUseNetNumbers=0
LabSize=60
